apiVersion: v1
kind: Service
metadata:
  namespace: three-tier
  name: postgres-svc
spec:
  selector:
    app: postgres
  ports:
  - name: postgres-svc
    protocol: TCP
    port: 5432
    targetPort: 5432
